### ISSUE TITLE
CustomAuthenticator.java:[8,9] method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by tpraneethsh** [Identicum/keycloak-custom-authenticator#4]
Hi,
while running, i am getting below error

[ERROR] /demo-keycloak/keycloak-custom-authenticator-master/src/main/java/com/identicum/keycloak/CustomAuthenticator.java:[8,9] method does not override or implement a method from a supertype

Below is the class.

public class CustomAuthenticator extends UsernamePasswordForm {
	**@Override
	protected String tempDisabledError**() {
		return Messages.ACCOUNT_TEMPORARILY_DISABLED;
	}
}

**Comment by chupetoide** [comment]
Hi @tpraneethsh,

Which Keycloak's version are you using ? The bruteforce error message is now part of the product:
https://github.com/keycloak/keycloak/blob/10.0.0/services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java#L223

If you want to compile the code just remove the `@Override` from the method `tempDisabledError()`.
